name: Frontend CI - Build & Push Image

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        run: |
          docker build \
            -t arunkumar885825/frontend:${{ github.sha }} \
            -t arunkumar885825/frontend:latest \
            .

      # 4️⃣ Push frontend image
      - name: Push frontend image
        run: |
          docker push arunkumar885825/frontend:${{ github.sha }}
          docker push arunkumar885825/frontend:latest

      # 5️⃣ Notify deployment repo (trigger CD)
      - name: Trigger deployment pipeline
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.DEPLOYMENT_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/arunkumar-create/deployment/dispatches \
            -d '{
              "event_type": "frontend_updated",
              "client_payload": {
                "tag": "'"${{ github.sha }}"'"
              }
            }'